global:
  config_version: 3
input:
  type: rsyslog
imports:
  - type: grok_patterns
    dir: logstash-patterns-core/patterns
metrics:
  - type: counter
    name: nginx_requests_total
    help: Total number of nginx requests.
    match: '%{QS:Host} %{QS:Url} %{NUMBER:RequestTime} %{POSINT:BytesSent} %{IP:RemoteAddr}'
    labels:
      host: '{{ gsub .Host "\"" ""}}'
      ip_version: '{{ $res := (gsub (gsub .RemoteAddr "^(((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(.|$)){4})$" "v4") "(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$" "v6") }}{{ if (and (ne $res "v4") (ne $res "v6")) }}{{$res}}{{ else }}{{ $res }}{{ end }}'
      #url: '{{ gsub .Url "\"" "" }}'

  - type: counter
    name: nginx_bytes_sent
    help: Total number of bytes transmitted by nginx.
    match: '%{QS:Host} %{QS:Url} %%{NUMBER:RequestTime} %{POSINT:BytesSent} %{IP:RemoteAddr}'
    value: '{{ .BytesSent }}'
    labels:
      host: '{{ gsub .Host "\"" "" }}'
      #url: '{{ gsub .Url "\"" "" }}'

  - type: histogram
    name: nginx_request_time
    help: Nginx request processing time.
    match: '%{QS:Host} %{QS:Url} %{NUMBER:RequestTime} %{POSINT:BytesSent} %{IP:RemoteAddr}'
    value: '{{ .RequestTime }}'
    buckets: [0.001, 0.005, 0.010, 0.025, 0.050, 0.100, 0.200, 0.500, 1.000, 5.00, 10.00]
    labels:
      host: '{{ gsub .Host "\"" "" }}'
      #url: '{{ gsub .Url "\"" "" }}'

server:
  protocol: http
  port: 9144